export { default as MpSwipe } from './swipe/swipe.vue'
export { default as MpSplitScreen } from './split-screen/split-screen.vue'
export { default as MpRetrospect } from './retrospect/retrospect.vue'
export { default as MpKibanaV } from './kibana-v/kibana-v.vue'
export { default as MpMapDataV } from './map-data-v/map-data-v.vue'
export { default as MpBookmark } from './bookmark/bookmark.vue'
