// 高亮要素
export const FEATURE_HIGHLIGHT = 'FEATURE_HIGHLIGHT'
// 清除要素高亮
export const CLEAR_FEATURE_HIGHLIGHT = 'CLEAR_FEATURE_HIGHLIGHT'
// 清除结果树选中
export const CLEAR_QUERY_TREE_SELECTED = 'CLEAR_QUERY_TREE_SELECTED'
